# version: '3.8'
services:
  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "dummy"
      AWS_SECRET_ACCESS_KEY: "dummy"
    depends_on:
      - dynamodb-local
    restart: unless-stopped

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512m"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8000/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      DEBUG: "${DEBUG:-0}"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"  # (auskommentiert für rootless)
    restart: unless-stopped
